# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70147af89c9cef72835973c84334035fea505fd9c8a7c1bc5304b183301ba98ad250abb020a68b7d0ffd728a784825034207c9329d33092bb193ae328c7d8729

test:
  secret_key_base: 75f8f324ea467040975e33e3a7e64d50218e1993366edfb0828e402fba959eb86799e06905637e0faea3b96cd8193d72930a4748b321c1bfd0fd12769a548b24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
